### PR TITLE
lib: properly write squashed ACI to disk

### LINKED ISSUE #73: failed to convert docker://kubernetes/redis-slave:v2
```
$ sudo /home/yifan/rkt/build-rkt-0.7.0+git/bin/rkt --debug=false --insecure-skip-verify=true fetch docker://kubernetes/redis-slave:v2
[sudo] password for yifan: 
Downloading 511136ea3c5a: [====================================] 32 B/32 B
Downloading f0dde87450ec: [====================================] 65.8 MB/65.8 MB
Downloading 76b658ecb564: [====================================] 71.5 KB/71.5 KB
Downloading 4faa69f72743: [====================================] 679 B/679 B
Downloading 2103b00b3fdf: [====================================] 32 B/32 B
Downloading 4303edc5e986: [====================================] 85.4 MB/85.4 MB
Downloading 14dfde0f38c5: [====================================] 643 B/643 B
Downloading d489fc3e869f: [====================================] 438 B/438 B
Downloading a8253f7d9cc1: [====================================] 22.7 KB/22.7 KB
Downloading 38cf7a363b14: [====================================] 32 B/32 B
Downloading d9343f29a1c4: [====================================] 32 B/32 B
Downloading 9cb3dca21a1f: [====================================] 32 B/32 B
Downloading c9eda0ec97c0: [====================================] 2.93 MB/2.93 MB
Downloading a44f8ddf5fb8: [====================================] 32 B/32 B
Downloading cf0fc1a9cd2b: [====================================] 32 B/32 B
Downloading 8567350addd7: [====================================] 32 B/32 B
Downloading dff9dfa9220d: [====================================] 32 B/32 B
Downloading 3fd8168c2f23: [====================================] 511 B/511 B
Downloading 85b1106c3ae7: [====================================] 544 B/544 B
Downloading 48a1e2b8f859: [====================================] 32 B/32 B
error converting docker image to ACI: error squashing image: error validating image: flate: corrupt input before offset 105339330
```

### PR DESCRIPTION
**Pull request by iaguis**
We were writing the file directly to its final destination instead of
writing it to a temporary file and then renaming it. This caused file
corruption when running docker2aci several times in parallel.

We now write the squashed ACI to a temporary file with a random name and
rename it atomically after the write is finished and the ACI validated.

Fixes #73

### CODE REVIEW

File: lib/docker2aci.go [hunk 1]
```diff
@@ -169,22 +169,27 @@ func SquashLayers(images []acirenderer.Image, aciRegistry acirenderer.ACIRegistr
...
 	squashedImagePath := path.Join(outputDir, squashedFilename)
 
-	squashedImageFile, err := os.Create(squashedImagePath)
+	squashedTempFile, err := ioutil.TempFile(outputDir, "squashedFilename-")
 	if err != nil {
 		return "", err
 	}
-	defer squashedImageFile.Close()
+	defer squashedTempFile.Close()
+	squashedTempFilePath := filepath.Join(outputDir, squashedTempFile.Name())
```
Comment (sgotti) [inline lib/docker2aci.go]: Is `filepath.Join` really needed?
squashedTempFile.Name() should just contain the outputDir.

I think that with this, if outputDir is `/tmp/something/` squashedTempFile will become `/tmp/something/tmp/something/filename`

Comment (iaguis) [inline lib/docker2aci.go]: You're right. I misinterpreted the `Name()` function.

File: lib/docker2aci.go [hunk 2]
```diff
@@ -167,24 +166,28 @@ func SquashLayers(images []acirenderer.Image, aciRegistry acirenderer.ACIRegistr
 	}
 
 	squashedFilename := getSquashedFilename(parsedDockerURL)
-	squashedImagePath := path.Join(outputDir, squashedFilename)
+	squashedImagePath := filepath.Join(outputDir, squashedFilename)
 
-	squashedImageFile, err := os.Create(squashedImagePath)
+	squashedTempFile, err := ioutil.TempFile(outputDir, "squashedFilename-")
```
Comment (sgotti) [inline lib/docker2aci.go]: Do you think that the tempFile should be removed on error?
Perhaps it can be created inside the tmpDir so it can be removed from who created it.

Comment (iaguis) [inline lib/docker2aci.go]: tmpDir can be in another filesystem and the Rename call would fail, I guess we should defer a function that checks if there was any error and removes the temp file :/

Comment (sgotti) [inline lib/docker2aci.go]: You're right!

Comment (iaguis) [inline lib/docker2aci.go]: Updated with tmp file removal

File: lib/docker2aci.go [hunk 3]
```diff
@@ -167,24 +166,39 @@ func SquashLayers(images []acirenderer.Image, aciRegistry acirenderer.ACIRegistr
...
 		return "", err
 	}
-	defer squashedImageFile.Close()
+	defer func() {
+		errClose := squashedTempFile.Close()
+		if err != nil {
+			// remove temp file on error
+			errRemove := os.Remove(squashedTempFile.Name())
+			if errRemove != nil {
+				err = errRemove
```
Comment (sgotti) [inline lib/docker2aci.go]: Will this mask the "real" error returned to the caller and/or return an error also if writeSquashedImage/ValidateACI complete successfully but Close() failed?

Comment (iaguis) [inline lib/docker2aci.go]: It will return the Remove error if there is one masking the "real" error.

If writeSquashedImage/ValidateACI complete successfully but Close() failed it will return the Close error.

Maybe we should return the "real" error instead of the Remove error? Not sure what's better.

Comment (sgotti) [inline lib/docker2aci.go]: > Maybe we should return the "real" error instead of the Remove error? Not sure what's better.

I've got the same doubts. I'll ignore the Close and the Remove errors to not mask the "real" one. (for example, Close() errors are often ignored: `defer file.Close()`)

Comment (iaguis) [inline lib/docker2aci.go]: I think it's important to not ignore the Close error on successful cases to avoid data corruption.

How about we remove the temp file on error ignoring the Remove errors so we don't mask the "real" one and we handle the close error if there was a successful execution?

```
defer func() {
	if err == nil {
		err = squashedTempFile.Close()
	} else {
		// remove temp file on error
		// we ignore its error to not mask the real error
		os.Remove(squashedTempFile.Name())
	}
}()
```

Comment (sgotti) [inline lib/docker2aci.go]: > I think it's important to not ignore the Close error on successful cases to avoid data corruption.

You're right.


> How about we remove the temp file on error ignoring the Remove errors so we don't mask the "real" one and we handle the close error if there was a successful execution?

Seems Good!

**Comment by iaguis** [comment]
Updated. PTAL

**Comment by sgotti** [comment]
LGTM!
