### PR TITLE
repository2: fix manifest v2.2 layer ordering.

### LINKED ISSUE #189: Layer ordering is somehow wrong on API v2.2
On 8a76b33 (right before we merged https://github.com/appc/docker2aci/pull/176):

```
$ docker2aci --version
docker2aci version v0.11.1-4-g8a76b33
appc version 0.8.2
$ docker2aci docker://nginx
Downloading sha256:51d229e136d [=============================] 19.8 MB / 19.8 MB
Downloading sha256:51f5c6a04d8 [=============================] 51.4 MB / 51.4 MB
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:bcd41daec8c [=============================]     194 B / 194 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B

Converted ports:
	name: "443-tcp", protocol: "tcp", port: 443, count: 1, socketActivated: false
	name: "80-tcp", protocol: "tcp", port: 80, count: 1, socketActivated: false

Generated ACI(s):
library-nginx-latest.aci
$ tar xvf library-nginx-latest.aci rootfs/etc/passwd
rootfs/etc/passwd
$ grep nginx rootfs/etc/passwd
nginx:x:104:107:nginx user,,,:/nonexistent:/bin/false
```

With current master:

```
$ docker2aci --version
docker2aci version v0.12.2-2-g54c5d94
appc version 0.8.5
$ docker2aci docker://nginx
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:51f5c6a04d8 [=============================] 51.4 MB / 51.4 MB
Downloading sha256:bcd41daec8c [=============================]     194 B / 194 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:a3ed95caeb0 [=============================]       32 B / 32 B
Downloading sha256:51d229e136d [=============================] 19.8 MB / 19.8 MB

Converted ports:
	name: "443-tcp", protocol: "tcp", port: 443, count: 1, socketActivated: false
	name: "80-tcp", protocol: "tcp", port: 80, count: 1, socketActivated: false

Generated ACI(s):
library-nginx-latest.aci
$ tar xvf library-nginx-latest.aci rootfs/etc/passwd
rootfs/etc/passwd
$ grep nginx rootfs/etc/passwd
$
```

cc @dgonyeo

### PR DESCRIPTION
**Pull request by sgotti**
With docker manifest v2.2 and oci the layers are ordered from the base layer to
the topmost layer.

This is just a quick fix for review. Next steps will be to add tests and remove duplicated layers.

Fixes #189

### CODE REVIEW

File: lib/internal/backend/repository/repository2.go [hunk 1]
```diff
@@ -254,8 +254,10 @@ func (rb *RepositoryBackend) buildACIV22(layerIDs []string, dockerURL *types.Par
 	var aciLayerPaths []string
 	var aciManifests []*schema.ImageManifest
 	var curPwl []string
-	for i := len(layerIDs) - 1; i > 0; i-- {
-		log.Debug("Generating layer ACI...")
+
+	log.Debug("Generating layer ACI...")
```
Comment (iaguis) [inline lib/internal/backend/repository/repository2.go]: why did you move this outside the loop?

Comment (sgotti) [inline lib/internal/backend/repository/repository2.go]: Because if there's only one layer it won't be written.

Comment (sgotti) [inline lib/internal/backend/repository/repository2.go]: Oh, I noticed that it should be written for every layer, will fix. Thanks!

**Comment by lucab** [comment]
I confirm this fixes troublesome containers that we've got reported so far, and LGTM (but I don't have any super-power here).

**Comment by lucab** [comment]
wrt duplicate layers, @sgotti privately pointed out that https://github.com/docker/distribution/issues/1527 is a relevant reference.
